import CompletionItem from '../../interfaces/completion.interface';

const CHANNEL: CompletionItem = {
  prefix: 'exp:channel:entries',
  items: [
    'author_id',
    'backspace',
    'cache',
    'refresh',
    'cat_limit',
    'category',
    'category_group',
    'channel',
    'disable',
    'display_by',
    'dynamic',
    'dynamic_parameters',
    'dynamic_start',
    'entry_id',
    'entry_id_from',
    'entry_id_to',
    'fixed_order',
    'group_id',
    'limit',
    'month_limit',
    'offset',
    'orderby',
    'paginate',
    'paginate_base',
    'paginate_type',
    'related_categories_mode',
    'relaxed_categories',
    'require_entry',
    'search:field_name',
    'show_current_week',
    'show_expired',
    'show_future_entries',
    'show_pages',
    'sort',
    'start_day',
    'start_on',
    'status',
    'stop_before',
    'sticky',
    'track_views',
    'uncategorized_entries',
    'url_title',
    'username',
    'week_sort',
    'year',
    'month',
    'day',
  ]
};

export default CHANNEL;